### ISSUE TITLE
Updates for beta5

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#192]
OK we can now start getting ready for beta5 templates. We should do this work in a new ```beta5``` branch and then when ready merge to ```master``` and then publish.

We have the following work ahead of us.
### Top priority items
 - [x] Create beta5 branch
 - [x] [ASP.NET Web API Template for Beta5](https://github.com/OmniSharp/generator-aspnet/issues/189)
 - [x] [ASP.NET Empty Template for Beta5](https://github.com/OmniSharp/generator-aspnet/issues/186)
 - [x] [ASP.NET Console App Template for Beta5](https://github.com/OmniSharp/generator-aspnet/issues/185)
 - [x] [ASP.NET Web App Template with Authentication for Beta5](https://github.com/OmniSharp/generator-aspnet/issues/191)
 - [x] [ASP.NET Class Library Template for Beta5](https://github.com/OmniSharp/generator-aspnet/issues/184)

### Can be added later
 - [x] [ASP.NET Client Side Item templates for Beta5](https://github.com/OmniSharp/generator-aspnet/issues/188)
 - [x] [ASP.NET Server Side Item templates for Beta5](https://github.com/OmniSharp/generator-aspnet/issues/187)
 - [x] [ASP.NET Web App Template with No Auth for Beta5](https://github.com/OmniSharp/generator-aspnet/issues/190)
 - [ ] [Update Nancy generator for beta5](https://github.com/OmniSharp/generator-aspnet/issues/197)
 - [ ] [Add beta5 xUnit test project](https://github.com/OmniSharp/generator-aspnet/issues/165)

We are hoping to get all changes in by the end of the day on Sunday 6/21 and ready to merge to master after that.

***If you think that you can help with one or more of the items please comment on the item so that we can assign the issue and avoid duplicate work.*** I'm planning to work on some of these items tomorrow. I've already created the beta5 branch so we can all start partying on this.

FYI I have created a label for beta5 issues, as well as priority labels. Queries are below. Lower priority means that it's more important.
 - [beta5 priority 1 issues](https://github.com/OmniSharp/generator-aspnet/issues?q=is%3Aopen+label%3Apriority-1)
 - [beta5 priority 2 issues](https://github.com/OmniSharp/generator-aspnet/issues?q=is%3Aopen+label%3Apriority-2)

***Note: beta5 is now on nuget.org, so the info below is no longer needed***

## How to test with beta5 before packages go to nuget.org

To be more specific about how to test with ```beta5``` before the packages go to nuget.org do the following.

 1. Add nuget.config file in the root of the project with the content below
 2. Invoke ```dnu restore -f https://nuget.org/api/v2/```

### nuget.config content
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="aspnetrelease" value="https://www.myget.org/F/aspnetbeta5/api/v2" />
  </packageSources>
</configuration>
```

#### Update 6/22
We have new feed locations for the packages they are listed below, I've updated the links above as well. Previous urls will stop working soon.

 - Feed: https://www.myget.org/F/aspnetbeta5/api/v2
 - Package list: https://www.myget.org/gallery/aspnetbeta5  

cc @peterblazejewicz @spboyer @rustd @mayurid

**Comment by rustd** [comment]
The only change required for Beta5 is to drop the timestamp from the package versions. The packages with no timestamp are not available on aspnet release feed so I didn't drop the timestamp since the samples won't work

**Comment by sayedihashimi** [comment]
@rustd can you give specific steps on how to test the templates today with the pre-release feed?

**Comment by rustd** [comment]
Set the NuGet feed to be https://www.myget.org/F/aspnetrelease

**Comment by Yantrio** [comment]
Nancy seems to be left off the list again?

**Comment by sayedihashimi** [comment]
@Yantrio sorry about that, it was not intentional. I was going off the list of issues that @rustd created, which was based off updates to Visual Studio.
Now that you mention it I also forgot about adding a unit test template. I've added both the this issue and marked the issues as ```beta5```.

@Yantrio can you help with the Nancy template?

**Comment by peterblazejewicz** [comment]
a note, I had `dnu` affair (not executable) so I had to make sure that `beta5` is used by dnvm instead of beta6:
```
dnvm use 1.0.0-beta5-11781
Adding /Users/piotrblazejewicz/.dnx/runtimes/dnx-mono.1.0.0-beta5-11781/bin to process PATH
```

**Comment by spboyer** [comment]
@peterblazejewicz @sayedihashimi - just now getting able to bring my head up for air. Is this the current status?

**Comment by peterblazejewicz** [comment]
@spboyer  I think you could:
- [ ] fetch `beta5` branch and review tests - I've expanded coverage to updated and added content
- [ ] review my changes - I could miss something covered by tests
- [ ] __test `build` and `run`__ - I've problem with `beta5` on my Mac and except of library/console application I was not able to build and run advanced content (`dnu . build` and `dnx . kestrel`).
I'll write myself a Vagrant box for aspnet to somehow overcome that problem now.

I've changed couple of things - for example there is no flattneded structure of template contents anymore - all is 1to1 compared to generated output, there are single templates with switches for Gulp/Grunt different logic, imports, etc.
Thanks!

**Comment by sayedihashimi** [comment]
At https://github.com/OmniSharp/generator-aspnet/issues/192 I have instructions on how to get it to work on Mac. It's working for me.

Note: there is a bad bug where kestrel will not stop when you use ```q```/```CTRL+C``` https://github.com/OmniSharp/generator-aspnet/issues/200. The workaround is to use ```CTRL+Z``` and then ```killall mono```. Unfortunately we will have to wait for ```beta6``` for the fix on that.

**Comment by sayedihashimi** [comment]
OK I have just released ```beta5``` to npmjs.org. I'll go ahead and close this item now. For the remaining items we can use [the query](https://github.com/OmniSharp/generator-aspnet/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Aenhancement+label%3Abeta5).

I will also create a new issue listing the known issues for beta5.

**Comment by sayedihashimi** [comment]
@peterblazejewicz @spboyer we should write a blog post on the ```beta5``` updates. The entry will be posted on the [official ASP.NET team blog](http://blogs.msdn.com/b/webdev/). Since @peterblazejewicz took care of the majority of the work I'd like to give him the first opportunity to author that if he's interested.

**Comment by peterblazejewicz** [comment]
@sayedihashimi I'm on my way home, still commuting. Before I'd write  something, it'll be a midnight here I think 😀

**Comment by sayedihashimi** [comment]
@peterblazejewicz ok that's not a problem. I'll be traveling tmrw anyway so likely can't post it until Friday.

**Comment by sayedihashimi** [comment]
Blog posted at http://blogs.msdn.com/b/webdev/archive/2015/07/04/updates-to-asp-net-5-yeoman-generators-for-beta-5.aspx, thanks @peterblazejewicz 

cc @mayurid @danroth27 @rustd
