### ISSUE TITLE
Updates for beta6

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#279]
The `beta6` release of asp.net 5 will be coming soon. The _target_ date is Monday 7/27, we would like to update `yo aspnet` on that same day if possible.

In this release the template changes are much less then in `beta5`. Also the refactoring work that was previously done by @peterblazejewicz will be very helpful to simplify the updates.

The work needed is listed below.
- [x] add a new [beta6](https://github.com/OmniSharp/generator-aspnet/tree/beta6) branch
- [x] add label
- [x] [ASP.NET 5 beta6 WebAPI template](https://github.com/OmniSharp/generator-aspnet/issues/278)
- [x] [ASP.NET 5 beta6 WebApp No Auth project](https://github.com/OmniSharp/generator-aspnet/issues/277)
- [x] [ASP.NET 5 beta6 WebApp with authentication template](https://github.com/OmniSharp/generator-aspnet/issues/276)
- [x] [ASP.NET5 Beta6 Empty Web Template](https://github.com/OmniSharp/generator-aspnet/issues/275) - ***assigned***
- [x] [ASP.NET 5 Beta6 Class Library project](https://github.com/OmniSharp/generator-aspnet/issues/274) - ***assigned***
- [x] [ASP.NET 5 Beta6 Console App Template](https://github.com/OmniSharp/generator-aspnet/issues/273)  - ***assigned***
- [x] Unit test project  - https://github.com/OmniSharp/generator-aspnet/issues/165
- [ ] Merge to `master` and `release` branches (_@sayedihashimi will take care of this when the release goes out_)

For this release the content changes are much less than what they were previously. I think the easiest way to implement the changes will be to use `yo aspnet` to generate a project with `beta5` and then diff to the `beta6` content and just make the changes. Copying the files will cause more heartache I think.

## How to install the beta6 runtime before it gets to nuget.org

Since the `beta6` runtime is not on `nuget.org` yet you'll have to go out of your way to install it from `myget.org`. Here is how to do that.

 1. Set the `DNX_FEED` env var to point to https://www.myget.org/F/aspnetbeta6/api/v2
 1. Call `dnvm install 1.0.0-beta6`

Here is the commands in the console.

```
Sayeds-MacBook-Pro:WebApplication sayedhashimi$ export DNX_FEED=https://www.myget.org/F/aspnetbeta6/api/v2
Sayeds-MacBook-Pro:WebApplication sayedhashimi$ dnvm install 1.0.0-beta6
Default stable feed (https://www.nuget.org/api/v2) is being overridden by the value of the DNX_FEED variable (https://www.myget.org/F/aspnetbeta6/api/v2).
Downloading dnx-mono.1.0.0-beta6 from https://www.myget.org/F/aspnetbeta6/api/v2
Download: https://www.myget.org/F/aspnetbeta6/api/v2/package/dnx-mono/1.0.0-beta6
######################################################################## 100.0%
Installing to /Users/sayedhashimi/.dnx/runtimes/dnx-mono.1.0.0-beta6
Adding /Users/sayedhashimi/.dnx/runtimes/dnx-mono.1.0.0-beta6/bin to process PATH
```

## How to test with beta6 before packages go to nuget.org

To be more specific about how to test with ```beta5``` before the packages go to nuget.org do the following.

 1. Add nuget.config file in the root of the project with the content below
 2. Invoke ```dnu restore -f https://nuget.org/api/v2/```

### nuget.config content
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="aspnetrelease" value="https://www.myget.org/F/aspnetbeta6/api/v2" />
  </packageSources>
</configuration>
```

## Feed urls
We have new feed locations for the packages they are listed below, I've updated the links above as well. Previous urls will stop working soon.

 - Feed: https://www.myget.org/F/aspnetbeta6/api/v2
 - Package list: https://www.myget.org/gallery/aspnetbeta6

**Comment by peterblazejewicz** [comment]
Label done:
https://github.com/OmniSharp/generator-aspnet/labels/beta6

**Comment by sayedihashimi** [comment]
@peterblazejewicz @Spinarooni thanks a lot for the contributions! I think that we are good to go here.

Once asp.net 5 beta6 goes out I'll merge to master and then release to get the npm package published.

I think we should put together a blog post for the [official ASP.NET team blog](http://blogs.msdn.com/b/webdev) similar to the [beta5 post](http://blogs.msdn.com/b/webdev/archive/2015/07/04/updates-to-asp-net-5-yeoman-generators-for-beta-5.aspx) by @peterblazejewicz.

I think we should offer @Spinarooni the first crack at that since he's a new contributor this round. @Spinarooni would you be interested? I'll clearly indicate that you're the author and you can link to your twitter/github if you like.

@mayurid @danroth27 @rustd we are good to go with beta6 `yo aspnet`.

**Comment by Spinarooni** [comment]
@sayedihashimi I appreciate the opportunity.  However I will not be available until Monday to do anything so if it's needed before then I would not be a good choice.

**Comment by sayedihashimi** [comment]
@Spinarooni no rush on the blog post. I think by the end of next week would be ideal.

**Comment by Spinarooni** [comment]
@sayedihashimi Ok, I'll try to put something together.  What format would this need to be in,  Markdown, Word, etc?

**Comment by sayedihashimi** [comment]
Ok I've published a new version to npmjs.org. I ran into an issue #292 so had to push manually.
