### ISSUE TITLE
Updates for beta7

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#308]
As @rustd posted beta7 announcement, here is a short tag list we usually do:

- [x] make [`beta7` branch](https://github.com/OmniSharp/generator-aspnet/tree/beta7)
- [x] add `beta7` label to tag content: https://github.com/OmniSharp/generator-aspnet/labels/beta7
- [x] [get build and development HOW-TO for contributors](https://github.com/OmniSharp/generator-aspnet/issues/319)
- [x] [ASP.NET Console](https://github.com/OmniSharp/generator-aspnet/issues/312)
- [x] [ASP.NET Class](https://github.com/OmniSharp/generator-aspnet/issues/313)
- [x] [ASP.NET Empty](https://github.com/OmniSharp/generator-aspnet/issues/314)
- [x] [ASP.NET Web API](https://github.com/OmniSharp/generator-aspnet/issues/315)
- [x] [ASP.NET Web App (No Auth)](https://github.com/OmniSharp/generator-aspnet/issues/316)
- [x] [ASP.NET Web App (individual Auth)](https://github.com/OmniSharp/generator-aspnet/issues/317)
- [x] [Update and review documentation](https://github.com/OmniSharp/generator-aspnet/issues/309)

Feel free to update tasks list

We need  label to tag other issues like: #304  or #298 

/cc @sayedihashimi

**Comment by sayedihashimi** [comment]
@rustd when you post the .zip files as issues we should update this issue with the links.

**Comment by rustd** [comment]
Feed used: https://www.myget.org/F/aspnetliterelease/api/v2 
Samples are here: https://onedrive.live.com/redir?resid=43459A6389A804D9%21102054

**Comment by rustd** [comment]
https://github.com/OmniSharp/generator-aspnet/issues/312
https://github.com/OmniSharp/generator-aspnet/issues/313
https://github.com/OmniSharp/generator-aspnet/issues/314
https://github.com/OmniSharp/generator-aspnet/issues/315
https://github.com/OmniSharp/generator-aspnet/issues/316
https://github.com/OmniSharp/generator-aspnet/issues/317

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
As you are releasing to NPM, can you make sure we have everything up and cleaned, so `beta7` branch could be created (and we are ready to go)
We have 3 pending PRs but I think they are not blockers here and there are no other tickets that could stop work with `beta7` branch.
Thanks!

**Comment by peterblazejewicz** [comment]
configuration for `beta7` in one ticket: https://github.com/OmniSharp/generator-aspnet/issues/319

**Comment by peterblazejewicz** [comment]
/cc
@Spinarooni

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
If we review documentation and ev. submit updates (the last task), the `beta7` is ready to ship

**Comment by sayedihashimi** [comment]
@peterblazejewicz ok sounds great. I've got the release process figured out. I'll release when beta7 goes out. I think that is today but need to double check.

**Comment by peterblazejewicz** [comment]
All tasks from above list are closed and PRs merged. The `beta7` branch is already merged.
You could see other issues/task related to `beta7` and their status here:
https://github.com/OmniSharp/generator-aspnet/labels/beta7
Thank!
