### ISSUE TITLE
RC1 Release tasks

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#468]
- [x] release tag `rc1`
- [x] branch `rc1` https://github.com/OmniSharp/generator-aspnet/tree/rc1
- [x] how-to notes #469
- [x] Class template project #462
- [x] Console template project #463
- [x] Empty Web App template project #464
- [x] Web API project #465
- [x] Web Application Basic project #466
- [x] Web Application with Authentication project #467
- [x] Docker configuration file review #473 
- [x] update yo aspnet:nuget subgenerator #476 
- [x] add  minimized version of site.js and site.css to projects #483 
- [x] issues review against `rc1` changes
- [x] documentation review
- [x] project readme review/cleanup #378 

The `rc1` is slated for November as release date.
> The November release candidate (RC1) will be a supported and production ready cross-platform release. 

https://github.com/aspnet/Home/wiki/Roadmap

https://www.myget.org/gallery/aspnetrc1

If you want to contribute please add a comment in related issue(s).

The tested configuration on OS X:
https://github.com/OmniSharp/generator-aspnet/issues/469

**Comment by sayedihashimi** [comment]
Thanks @peterblazejewicz. I think we have completed all critical tasks for `rc1`.

**Comment by spboyer** [comment]
All `rc1` items have been reviewed and merged

**Comment by peterblazejewicz** [comment]
I've updated issues and closing this one :)
