### ISSUE TITLE
RC2 Release tasks

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/generator-aspnet#601]
- [x] .NET Web App (StarterWeb with Auth) template for RC2 #638 > #653 #655 #656 #657 #658 #659
- [x] xUnit tests template for RC2 #639
- [x] Nancy template update for RC2 #640
- [x] Dockerfile(s) #532 #685 
- [x] Usage/hints review for RC2: #603 
- [x] rc2 branch: https://github.com/OmniSharp/generator-aspnet/tree/rc2
- [x] label https://github.com/OmniSharp/generator-aspnet/labels/rc2
- [x] rc2 release/tooling info: #602 
- [x] ConsoleApp #600 > #611 
- [x] Class Library #599 > #609 
- [x] Web Application #598 > #612 
- [x] Empty Web Application #597 > #608 
- [x] .NET Core Console App template for RC2 > #633 
- [x] .NET WebAPI App template for RC2 #633 > #634 
- [x] Review Semantic UI Empty Web Application #613 
- [x] _Empty_ generator rename to _Empty Web_ #587 >  #606 
- [x] Drop e2etest #607 > #610 
- [x] Update aspnet:Middleware subgenerator #614 > #625
- [x] Update aspnet:MvcController subgenerator #615 > #626
- [x] Add `aspnet:Program` subgenerator #616 > #627
- [x] Update aspnet:nuget subgenerator #617 > #629 
- [x] Update aspnet:StartupClass subgenerator #618 > #628 
- [x] Update aspnet:TagHelper subgenerator #619 > #630 
- [x] Update aspnet:UserSecrets subgenerator #620 > #631
- [x] Update aspnet:WebApiContoller subgenerator #621 > #636
- [x] Drop aspnet:JScript subgenerator alias to aspnet:JavaScript for RC2 #622 > #623
