### ISSUE TITLE
Update templates to match vs2017 rc

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#846]
We recently released VS2017 RC which has the latest tooling support for asp.net core. I'm sorry I didn't start this process earlier.

I've gathered up all the template content. We have a new template that we shipped in VS2017 RC. FYI we have an xUnit template in VS2017 out of the box. I believe the xUnit template here in yo aspnet helped make that happen.

Below are a list of issues that I've created for this work.

 - [x] #838 - Console
 - [x] #839 - Class lib
 - [x] #840 - Empty web
 - [x] #841 - Web app
 - [x] #842 - Web app ind auth
 - [x] #843 - Web api
 - [x] #844 - XUnit
- [x] #845 - MSTest
- [x] #863 Options to specify runtim version
- [x] Project https://github.com/OmniSharp/generator-aspnet/projects
- [x] #862 (Branch for vs2017-rc)
- [x] #865 `usersecrets` sub-generator fate under vs2017-rc
- [x] #867 discuss/created replacement for README.md
- [x] #885 Update F# WebBasic (web starter) project for RC vs2017-rc
- [x] #884 Update F# WebApi project for RC# vs2017-rc
- [x] #883 Update F# xUnit Test project for RC vs2017-rc
- [x] #882 Update F# ClassLibrary project for RC vs2017-rc
- [x] #881 Update F# EmptyWeb project for RC vs2017-rc
- [x] #880 Update F# ConsoleApp for RC vs2017-rc
- [x] #889 Add F# MSTest project template vs2017-rc
- [x] #909 Update `nuget` generator
- [x] #910 Add 'webconfig' generator
- [x] #911 Remove 'usersecrets' for RC

I think that is all of them. If I forgot any let me know.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
I think the 1.0.1 was not marked/tagged on aspnet/Templates:
https://github.com/aspnet/Templates/releases
There is an 1.0.1 branch, but it seems to be outdated:
https://github.com/aspnet/Templates/commits/rel/1.0.1

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
We need to tailor out the routine to verify template content. At the moment I'm not able to restore/build the simplest template(s) from samples: https://github.com/sayedihashimi/aspnettemplates/tree/vs2017rc/samples
My `dotnet/cli` (SDK 1.0.2 from download page) does not work as it expects `project.json` files
(`warn : The folder '/Users/piotrblazejewicz/git/aspnettemplates/samples/ClassLibrary1' does not contain a project to restore.`)
```
.NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551
```

**Comment by sayedihashimi** [comment]
>I think the 1.0.1 was not marked/tagged on aspnet/Templates:
https://github.com/aspnet/Templates/releases
There is an 1.0.1 branch, but it seems to be outdated:
https://github.com/aspnet/Templates/commits/rel/1.0.1

@mlorbetske @seancpeters in which branch can we find the latest template content?

>My dotnet/cli (SDK 1.0.2 from download page) does not work as it expects project.json files
(warn : The folder '/Users/piotrblazejewicz/git/aspnettemplates/samples/ClassLibrary1' does not contain a project to restore.)

I think the issue is that you need a newer CLI. See below.

```
> dotnet --version
1.0.0-preview3-004056
C:\Data\mycode\aspnettemplates\samples\ConsoleApp1 [vs2017rc ≡]
> dotnet restore
  Restoring packages for C:\Data\mycode\aspnettemplates\samples\ConsoleApp1\ConsoleApp1.csproj...
  Lock file has not changed. Skipping lock file write. Path: C:\Data\mycode\aspnettemplates\samples\ConsoleApp1\obj\project.assets.json
  Generating MSBuild file C:\Data\mycode\aspnettemplates\samples\ConsoleApp1\obj\ConsoleApp1.csproj.nuget.g.targets.
  Generating MSBuild file C:\Data\mycode\aspnettemplates\samples\ConsoleApp1\obj\ConsoleApp1.csproj.nuget.g.props.
  Restore completed in 422.6902ms for C:\Data\mycode\aspnettemplates\samples\ConsoleApp1\ConsoleApp1.csproj.

  NuGet Config files used:
      C:\Users\sayedha\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
      https://dotnet.myget.org/F/dotnet-web/api/v3/index.json
      https://dotnet.myget.org/F/nuget-build/api/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
C:\Data\mycode\aspnettemplates\samples\ConsoleApp1 [vs2017rc ≡]
```

>We need to tailor out the routine to verify template content. A

Sorry about the confusion this release. I should have started this much sooner, that was my fault. Going forward I'm hoping that we can leverage `dotnet new` to simplify this entire process. I'll email you about setting up a meeting so that we can discuss that.

**Comment by peterblazejewicz** [comment]
Sayed, can you discuss with team what is the state of project.json > csproj described here?
https://github.com/dotnet/cli/blob/e938933a7ea4e4542db142a3a767be83404e2e12/Documentation/ProjectJsonToCSProj.md


> I think the issue is that you need a newer CLI. See below.

Sorry Sayed, the 1.0.2 (older then 1.0.1) is `1.0.0-preview2-003148`. The 1.1 (1.0.0-preview2-1-003177) is:
```
Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576
```
They comes from SDK installers from dot.net page. So they are *preview-2* all. As mentioned on the Twitter, the Visual Studio Preview for Mac ships with .sln and .csproj:
```bahs
ls -1
MyCoolApp.csproj
Program.cs
Startup.cs
bin
obj
wwwroot
```
so that's not possible to run this with `dotnet run` using 1.1 SDK tools:
```bash
warn : The folder '/Users/piotrblazejewicz/git/MyCoolApp/src/MyCoolApp' 
does not contain a project to restore.
```
```bash
The current project is not valid because of the following errors:
/Users/piotrblazejewicz/git/MyCoolApp/src/MyCoolApp(1,0): error DOTNET1017: 
Project file does not exist '/Users/piotrblazejewicz/git/MyCoolApp/src/MyCoolApp/project.json'.
```

I think - as with previous release, one needs a clear blueprint how to install tools, update content to make update happen, like here: https://github.com/OmniSharp/generator-aspnet/issues/760#issue-161972272

**Comment by sayedihashimi** [comment]
>Sayed, can you discuss with team what is the state of project.json > csproj described here?
https://github.com/dotnet/cli/blob/e938933a7ea4e4542db142a3a767be83404e2e12/Documentation/ProjectJsonToCSProj.md

@peterblazejewicz we just released the first version of the .csproj support. `project.json` is going away for .net core. VS2017 RC only supports .csproj based .net core projects.

There are two "worlds" here for .net core currently. The `project.json` world and the `.csproj` world. The tools you have installed on your machine are `project.json` based it looks like.

I just installed the latest ***.NET Core SDK Installer*** from https://github.com/dotnet/cli and tried with the console project in the samples, it was working. See messages below.

```
c:\data\mycode\aspnettemplates\samples\ClassLibrary1>dotnet --version
1.0.0-preview4-004107

c:\data\mycode\aspnettemplates\samples\ClassLibrary1>dotnet restore
  Restoring packages for c:\data\mycode\aspnettemplates\samples\ClassLibrary1\ClassLibrary1.csproj...
  Lock file has not changed. Skipping lock file write. Path: c:\data\mycode\aspnettemplates\samples\ClassLibrary1\obj\project.assets.json
  Generating MSBuild file c:\data\mycode\aspnettemplates\samples\ClassLibrary1\obj\ClassLibrary1.csproj.nuget.g.targets.
  Generating MSBuild file c:\data\mycode\aspnettemplates\samples\ClassLibrary1\obj\ClassLibrary1.csproj.nuget.g.props.
  Restore completed in 272.9268ms for c:\data\mycode\aspnettemplates\samples\ClassLibrary1\ClassLibrary1.csproj.

  NuGet Config files used:
      C:\Users\sayedha\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

I think on your box you somehow have a newer build of the CLI but it's from a `project.json` based branch. I left my Mac at work so I can't verify the installer there, but I'd be pretty surprised if it doesn't work. Can you install the latest from the download page https://github.com/dotnet/cli and let me know if you're still running into issues?

**Comment by peterblazejewicz** [comment]
I've used build from dot.net as mentioned. Should I use build from dotnet/cli instead? The point of this question is that users won't be able to quickly grab correct runtime. Here are releases:
https://github.com/aspnet/home/releases
https://www.microsoft.com/net/download/core
I've installed Preview 4 build and it does work with .csproj. But it supports 1.0.1 runtime version, not 1.0.2 (now officially distribute by dotnet/core download LTS) or 1.1 (as Current)
Hence my all this questions. That's why I asked to review topic with MS tooling team to get clear picture what you folks want to provide in the first place.

**Comment by sayedihashimi** [comment]
@peterblazejewicz thanks. I think I understand. From https://dot.net when you go to the [download page](https://www.microsoft.com/net/download/core) there are two tabs; ***LTS*** and ***Current***. I have screenshots below. 

## LTS download tab

![lts](https://cloud.githubusercontent.com/assets/1283154/20464875/b7918256-af05-11e6-83f8-fbce2b245d40.PNG)

## Current download tab

![current](https://cloud.githubusercontent.com/assets/1283154/20464876/ba6fe22e-af05-11e6-89a2-00446c082223.PNG)

In your case you have the ***LTS*** version installed, which supports `project.json` and I have the ***Current*** version which supports `.csproj`.

I think it makes sense for the download page to default to LTS because there is a higher level of support there, and the primary purpose of that page is to download runtime bits.

I think it makes sense for `yo aspnet` to default to the latest instead because:

 - It matches the latest support found in Visual Studio
 - `project.json` is going away for .NET Core projects, `.csproj` is the future.
 - For `project.json` users they can use the previous version of `yo aspnet`. We could even upgrade the template content to use latest packages and release a different version if there is enough interest. In contrast, for CLI users there is no other tool (besides `dotnet new` which is very basic currently) to get started with a .csproj based project for .NET Core.

I'm hoping that users will download the ***LTS*** for the apps that they are already running today, but use ***Current*** for development of new projects. .NET Core users that are on `project.json` will have to migrate to `.csproj`. VS2017 RC doesn't support `project.json` based .NET Core projects.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
Check with folks in MS if dotnet/download for mac really ship support for .csproj.
I've got this as explained before for *Current*:
```
 ~ dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```
(I've installed it again to verify what I'm writing).
This version does not support `.csproj` at all.
The `dotnet new` creates:
```
ls -1
Program.cs
project.json
```
The existing projects couldn't be run:
```
dotnet run
The current project is not valid because of the following errors:
/Users/piotrblazejewicz/git/aspnettemplates/samples/ConsoleApp1(1,0): error DOTNET1017: Project file does not exist '/Users/piotrblazejewicz/git/aspnettemplates/samples/ConsoleApp1/project.json'.
```

It could be that *Current* version of installer for Mac OS X ships different bits than one for Windows. I do understand that you expect `.csproj` support in 1.1. I've seen topics like these one (for Windows OS):
https://github.com/dotnet/cli/issues/4788

Yes, I could use bits from github/cli home page: `1.0.0-preview4-004107` on Mac OS X.
Sorry for behaving like a jerk, but that's how things seem to look like now with tooling.

**Comment by sayedihashimi** [comment]
@balachir @mlorbetske @glennc I'm hearing from @peterblazejewicz that he's having a hard time getting `dotnet` cli to support `.csproj` based project on a Mac. He is getting the ***Current*** installer from https://dot.net.

**Comment by ivanmartinvalle** [comment]
@peterblazejewicz Thank you! I was having this exact same issue (not seeing any .csproj things in the new tooling), and downloading preview for directly from the GitHub page fixed it for me.

I did have an issue where opening the project in Visual Studio Code no longer automatically added launch.json and tasks.json, and raised that issue at https://github.com/OmniSharp/omnisharp-vscode/issues/982.

**Comment by glennc** [comment]
@blackdwarf

**Comment by blackdwarf** [comment]
Folks, sorry for the confusion. The tools that support Current are at preview2.1 and they are still project.json based. That means no csproj support. 

However, further previews (3, 4 etc.) are all csproj-based. You can download them:

* By going to the https://github.com/dotnet/cli repo and using the links from the README to get the latest.
* By going to https://github.com/dotnet/core/blob/master/release-notes/preview3-download.md and using the links to download the Preview 3 bits

The Preview 3 is not based on Current, however, the tools (and runtimes) install side-by-side so you can use them in this manner. https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md has more details on the how. 

Hope this clears it up.

**Comment by peterblazejewicz** [comment]
Most of the content is updated, rest is removed, the Nancy is left to be revisited and updated.
Some templates are more updated then from dotnet/templating. The SQLite actually works better (the dotnet RC does not work, filled bug).
See project for details of work:
https://github.com/OmniSharp/generator-aspnet/projects/1
